### ISSUE TITLE
 Verification failures on ARMv6, 32-bit, little-endian, Raspberry Pi B

### ISSUE THREAD

**Issue by darkk** [rurban/smhasher#299]
Building SMHasher with OpenWrt GCC 12.3.0 r24012-d8dd03c46f (toolchain-arm_arm1176jzf-s+vfp_gcc-12.3.0_musl_eabi) with `-O2 -DHAVE_NEON` highlights following failures:
- [ ] `    blake3_c - Verification value 0x50E4CD91 ....... FAIL! (Expected 0x58571F56)`, same as #297 
- [ ] `tabulation32 - Verification value 0xCC4CFFDC ....... FAIL! (Expected 0x335F64EA)`, same as #297
- [ ] `     polymur - Verification value 0xA612032C ....... FAIL! (Expected 0x4F894810)`, same as #297
- [ ] `      FNV128 - Verification value 0x000000BA ....... FAIL! (Expected 0xBCAA1426)`, same as #296
- [ ] `   superfast - Verification value 0x6306A6FE ....... FAIL! (Expected 0x0C80403A)`
